// Fill out your copyright notice in the Description page of Project Settings.


#include "LoginComp.h"
#include "HttpModule.h"
#include "IWebSocket.h"
#include "JsonObjectConverter.h"
#include "LogItemComp.h"
#include "UserStruct.h"
#include "WebSocketsModule.h"
#include "Blueprint/UserWidget.h"
#include "Components/EditableTextBox.h"
#include "Components/SizeBox.h"
#include "Components/TextBlock.h"
#include "Components/VerticalBox.h"
#include "Components/WrapBox.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "GameFramework/SpringArmComponent.h"
#include "Interfaces/IHttpRequest.h"
#include "Interfaces/IHttpResponse.h"
#include "Kismet/GameplayStatics.h"
#include "PLAI/Item/GameInstance/WorldGi.h"
#include "PLAI/Item/ItemComp/InvenComp.h"
#include "PLAI/Item/Npc/NpcNet.h"
#include "PLAI/Item/TestPlayer/TestPlayer.h"
#include "PLAI/Item/TestPlayer/TraitStructTable/TraitStructTable.h"
#include "PLAI/Item/UI/Character/UIChaStat.h"
#include "PLAI/Item/UI/Inventory/EquipInven/EquipInven.h"
#include "PLAI/Item/UI/Inventory/ItemInven/ItemInven.h"
#include "PLAI/Item/UI/Inventory/Map/QuestOrderActor.h"
#include "PLAI/Item/UI/Main/UIChaMain.h"
#include "PLAI/Item/UI/Main/UiChaView.h"
#include "PLAI/Item/UI/Main/UIinitMain.h"
#include "PLAI/Item/UI/Main/UiSign.h"

// Sets default values for this component's properties
ULoginComp::ULoginComp()
{ PrimaryComponentTick.bCanEverTick = true; }

void ULoginComp::BeginPlay()
{
	Super::BeginPlay();
	
    if (FModuleManager::Get().IsModuleLoaded("WebSocket"))
    {
    	FModuleManager::Get().LoadModule("WebSocket");
    }
	
    TestPlayer = Cast<ATestPlayer>(GetOwner());
	if (TestPlayer->IsLocallyControlled())
	{
		if (UWorldGi* WorldGi = Cast<UWorldGi>(GetWorld()->GetGameInstance()))
		{
			UE_LOG(LogTemp,Warning,TEXT("ULoginComp::BeginPlay WorldGi MonType Îì§Í≥†Ïò§Í∏∞ %s"),*UEnum::GetValueAsString(WorldGi->MonsterType));
			if (WorldGi->MonsterType == EMonsterType::Boss)
			{
				TArray<AActor*>Nets;
				UGameplayStatics::GetAllActorsOfClass(GetWorld(), ANpcNet::StaticClass(),Nets);
				for (int i=0;i<Nets.Num();i++)
				{
					if (ANpcNet* Net = Cast<ANpcNet>(Nets[i]))
					{
						UE_LOG(LogTemp,Warning,TEXT("UIMOnWorld NetNpc Ï∞æÎäîÏ§ë %s"),*Net->personality)
						
						if (Net->NpcNameString == FString("Bass"))
						{
							Net->personality = FString(TEXT("ÏäπÎ¶¨Ïóê Ï∑®Ìïú"));
							UE_LOG(LogTemp,Warning,TEXT("UIMOnWorld Npc ÏÑ±Í≤© Î∞îÍæ∏Í∏∞ %s"),*Net->personality)
						}
					}
				}
			}
			if (WorldGi->Creature) { TestPlayer->InvenComp->Server_SpawnCreature(); WorldGi->Creature = nullptr; }
			// ÏµúÏ¥à Í≤åÏûÑ Ïã§Ìñâ ÌñàÎäîÏßÄ
			if (WorldGi->bGameStart == false)
			{
				UiMain = CreateWidget<UUiMain>(GetWorld(),UiMainFactory);
				UiMain->AddToViewport(2);
				UiMain->LoginComp = this;
				UiMain->WbpUiSign->LoginComp = this;
			}
			else
			{
				if (WorldGi->bBattleReward == true || WorldGi->bGameStart == true)
				{
					UE_LOG(LogTemp, Warning, TEXT("LoginComp Ïù¥ÎØ∏ Ï†ëÏÜçÌïú Ï∫êÎ¶≠ÌÑ∞ Gi UserFullInfo Î∂àÎü¨Ïò§Í∏∞"));
					UserFullInfo = WorldGi->UserFullInfoGi;
					HttpMePost();

					if (WorldGi->bBattleReward == true)
					{
						FTimerHandle TimerHandle;
						GetWorld()->GetTimerManager().SetTimer(TimerHandle,[this,WorldGi]()
						{ TestPlayer->InvenComp->TurnReward(); WorldGi->bBattleReward = false;},1.0,false);
					}
					// if (WorldGi->bBattleReward == true){UE_LOG(LogTemp,Warning,TEXT("LoginComp Ï†ÑÌà¨ X Î≥¥ÏÉÅ X")) return;}
				}
			}
		}
	}
}


// Called every frame
void ULoginComp::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);
	
	if (APlayerController* PC = Cast<APlayerController>(TestPlayer->GetController()))
	{
		if (TestPlayer->IsLocallyControlled() && PC->WasInputKeyJustPressed(EKeys::LeftMouseButton))
		{
		    FHitResult Hit;
		    PC->GetHitResultUnderCursor(ECC_Visibility, true, Hit);
		    if (Hit.bBlockingHit)
		    {
			    if (ANpcNet * NpcNet = Cast<ANpcNet>(Hit.GetActor()))
			    {
			    	if (NpcNet->UIPost == nullptr)
			    	{
			    		NpcNet->OpenQuest();
			    		if (AQuestOrderActor* QuestOrderActor = Cast<AQuestOrderActor>(NpcNet->QuestActorComponent->GetChildActor()))
			    		{
			    			if (QuestOrderActor->QuestType == EQuestType::B_NetNpcHearty)
			    			{ TestPlayer->InvenComp->MenuInven->Wbp_UiWorldMap->NextQuestType(EQuestType::C_NetNpcScared); }
			    			else if (QuestOrderActor->QuestType == EQuestType::C_NetNpcScared)
			    			{ TestPlayer->InvenComp->MenuInven->Wbp_UiWorldMap->NextQuestType(EQuestType::D_Store); }
			    		}
			    	}
			    	else
			    	{
			    		if (!NpcNet || !NpcNet->UIPost) return;
			    		NpcNet->UIPost->RemoveFromParent();
			    		NpcNet->UIPost = nullptr;
			    	}
			    }
		    }
		};
	}
}

void ULoginComp::HttpLoginPost()
{
    FNgrok Ngrok;
	
	FHttpRequestRef httpRequest = FHttpModule::Get().CreateRequest();

	httpRequest->SetURL(Ngrok.Ngrok + TEXT("/users/login"));
	httpRequest->SetVerb("POST");
	httpRequest->SetHeader(TEXT("Content-Type"), TEXT("application/json"));
	
	FLoginStruct LoginStruct;
	
	LoginStruct.email = UiMain->LoginId->GetText().ToString();
	LoginStruct.password = UiMain->LoginPw->GetText().ToString();

	FString JsonString;
	FJsonObjectConverter::UStructToJsonObjectString(LoginStruct, JsonString);
	httpRequest->SetContentAsString(JsonString);
	httpRequest->OnProcessRequestComplete().BindLambda([this](FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bProcessedSuccessfully)
	{
		FLoginStructGet LoginStructGetInit;
		FLoginStructGet LoginStructGet;
		if (bProcessedSuccessfully)
		{ FString JsonString = HttpResponse->GetContentAsString();
			UE_LOG(LogTemp, Warning, TEXT("Î°úÍ∑∏Ïù∏Ïª¥ÌîÑ ÌÜµÏã†ÏÑ±Í≥µ Î°úÍ∑∏Ïù∏ JsonStringÎ¨¥Ïóá [%s]"), *JsonString);

			FJsonObjectConverter::JsonObjectStringToUStruct(JsonString, &LoginStructGet);
			if (LoginStructGetInit.user_id != LoginStructGet.user_id)
			{ OnLogin.ExecuteIfBound(true);
				UE_LOG(LogTemp, Error, TEXT("Î°úÍ∑∏Ïù∏Ïª¥ÌîÑ ÌÜµÏã†ÏÑ±Í≥µ Î°úÍ∑∏Ïù∏ User IdÎäî? [%s]"),*LoginStructGet.user_id);
				UserFullInfo.user_id = LoginStructGet.user_id;
				// ÎãµÎ≥ÄÏù¥ Ïò® ÎîúÎ¶¨Í≤åÏù¥Ìä∏ÏóêÎã§Í∞Ä meÎ•º Ìï¥ÏïºÌï†ÎìØ
				UE_LOG(LogTemp, Display , TEXT("UiMain HttpLoginMe Î≥¥ÎÇ¥Ïûê"));
				UiMain->HttpLoginMe();
			}
			else
			{ OnLogin.ExecuteIfBound(false);
				UE_LOG(LogTemp, Warning, TEXT("Î°úÍ∑∏Ïù∏Ïª¥ÌîÑ ÌÜµÏã†ÏÑ±Í≥µ Î°úÍ∑∏Ïù∏ Ïã§Ìå®")); }
		}
	});
	httpRequest->ProcessRequest();
}


void ULoginComp::HttpSignPost()
{
	FHttpRequestRef httpRequest = FHttpModule::Get().CreateRequest();
	FNgrok Ngrok;
    FString url = FString::Printf(TEXT("%s/users/register"),*Ngrok.Ngrok);
	httpRequest->SetURL(url);
	httpRequest->SetVerb("POST");
	httpRequest->SetHeader(TEXT("Content-Type"), TEXT("application/json"));

	FLoginStruct LoginStruct;
	LoginStruct.email = UiMain->WbpUiSign->SignId->GetText().ToString();
	LoginStruct.password = UiMain->WbpUiSign->SignPw->GetText().ToString();

	FString JsonString;
	FJsonObjectConverter::UStructToJsonObjectString(LoginStruct, JsonString);
	httpRequest->SetContentAsString(JsonString);
	
	httpRequest->OnProcessRequestComplete().BindLambda([this](FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bProcessedSuccessfully)
	{
		if (bProcessedSuccessfully)
		{
			FString JsonString = HttpResponse->GetContentAsString();
			UE_LOG(LogTemp,Warning,TEXT("Î°úÍ∑∏Ïù∏Ïª¥ÌîÑ Í∞ÄÏûÖÏöîÏ≤≠ ÏÑ±Í≥µ %s ÎãµÎ≥ÄÏΩîÎìú %d"),*JsonString,HttpResponse->GetResponseCode());
			if (UiMain->WbpUiSign)
			{
				UiMain->WbpUiSign->SignCompleteBox->SetVisibility(ESlateVisibility::Visible);
				if (HttpResponse->GetResponseCode() == 200)
				{ UiMain->WbpUiSign->bSingComplete->SetText(FText::FromString(TEXT("Í∞ÄÏûÖ ÏôÑÎ£å"))); }
				else
				{ UiMain->WbpUiSign->bSingComplete->SetText(FText::FromString(TEXT("Í∞ÄÏûÖ Ïã§Ìå®")));
					UiMain->WbpUiSign->bSingCompleteDetail->SetText(FText::FromString(JsonString)); }
			}
		}
		else
		{
			UE_LOG(LogTemp,Warning,TEXT("Î°úÍ∑∏Ïù∏Ïª¥ÌîÑ Í∞ÄÏûÖÏöîÏ≤≠ Ïã§Ìå® %d"),HttpResponse->GetResponseCode());
		}
	});
	httpRequest->ProcessRequest();
}

void ULoginComp::Server_HttpMePost_Implementation()
{ Client_HttpMePost(); }

void ULoginComp::Client_HttpMePost_Implementation()
{ HttpMePost(); }

void ULoginComp::HttpMePost()
{
	FHttpRequestRef httpRequest = FHttpModule::Get().CreateRequest(); FNgrok Ngrok;
	FString url = FString::Printf(TEXT("%s/me/"),*Ngrok.Ngrok);

	httpRequest->SetURL(url);
	httpRequest->SetVerb("POST");
	httpRequest->SetHeader(TEXT("Content-Type"), TEXT("application/json"));

	FString JsonString;
	FMeStruct MeStruct;
	
	MeStruct.user_id = UserFullInfo.user_id;
	
	FJsonObjectConverter::UStructToJsonObjectString(MeStruct,JsonString);
	httpRequest->SetContentAsString(JsonString);
	httpRequest->OnProcessRequestComplete().BindLambda([this](FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bProcessedSuccessfully)
	{
		if (bProcessedSuccessfully)
		{
			FString JsonString = HttpResponse->GetContentAsString();
			UE_LOG(LogTemp,Warning,TEXT("Î°úÍ∑∏Ïù∏Ïª¥ÌîÑ ÎÇòÏùòÏ†ïÎ≥¥ GetAsContetAsStringÎêú Ï†úÏù¥Ïä®Í∞í ÏÑ±Í≥µ %s"),*JsonString);
			
			if (JsonString.IsEmpty())
			{
				UE_LOG(LogTemp, Error, TEXT("Login Comp // ÏÑúÎ≤Ñ ÏùëÎãµÏùÄ ÏÑ±Í≥µÌñàÏßÄÎßå ÎÇ¥Ïö©Ïù¥ ÎπÑÏóàÏäµÎãàÎã§."));
				return;
			}
			// 2. JSON ‚Üí Struct ÌååÏã± ÏãúÎèÑ
			if (!FJsonObjectConverter::JsonObjectStringToUStruct(JsonString, &UserFullInfo))
			{
				UE_LOG(LogTemp, Error, TEXT("Login Comp // JSON ÌååÏã± Ïã§Ìå®: Íµ¨Ï°∞Ï≤¥ Î≥ÄÌôòÏóê Ïã§Ìå®ÌñàÏäµÎãàÎã§."));
				return;
			}
			// 3. ÌååÏã± ÏÑ±Í≥µÌñàÎçîÎùºÎèÑ, ÌïÑÏàò Í∞íÏù¥ Îì§Ïñ¥ÏûàÎäîÏßÄ Ïú†Ìö®ÏÑ± Í≤ÄÏÇ¨
			if (UserFullInfo.character_info.character_id.IsEmpty())
			{
				UE_LOG(LogTemp, Error, TEXT("Login Comp // UserFullInfo ÌïÑÏàò Í∞íÏù¥ ÎπÑÏñ¥ ÏûàÏùå (character_id ÏóÜÏùå)."));
				return;
			}
			
			UE_LOG(LogTemp,Warning,TEXT("Î°úÍ∑∏Ïù∏Ïª¥ÌîÑ ÎÇòÏùòÏ†ïÎ≥¥ Ï°∞Ìöå ÏÑ±Í≥µ %s"),*JsonString);
			FJsonObjectConverter::JsonObjectStringToUStruct(JsonString, &UserFullInfo);
			// FString GetJson;
			// FJsonObjectConverter::UStructToJsonObjectString(UserFullInfo,GetJson);
			// UE_LOG(LogTemp,Warning,TEXT("Î°úÍ∑∏Ïù∏Ïª¥ÌîÑ ÎÇòÏùòÏ†ïÎ≥¥ Ï°∞Ìöå JsonÎ≥ÄÌôò %s"),*GetJson);

			if (UiMain)
			{ UiMain->Wbp_UIChaMain->SetUiChaStat(&UserFullInfo);
				FUserFullInfo InitUserFullInfo; }
			else
			{ UE_LOG(LogTemp,Warning,TEXT("LoginComp ÌÑ¥Ï†úÌõÑ ÎÑòÏñ¥Ïò§Î©¥ UiMainÏù¥ ÏóÜÏñ¥Ïöî")); }
			
			TestPlayer->InvenComp->MenuInven->Wbp_UIChaStat->SetUiChaStat(&UserFullInfo);
			LoadEquipItem();
			LoadInvenItem();
			
			TestPlayer->InvenComp->MenuInven->Wbp_ChaView->NameCha->SetText
			(FText::FromString(UserFullInfo.character_info.character_name));
			TestPlayer->InvenComp->MenuInven->Wbp_ChaView->JobCha->SetText
			(FText::FromString(UserFullInfo.character_info.job));
			TestPlayer->InvenComp->MenuInven->Wbp_ChaView->LevCha->SetText
			(FText::AsNumber(UserFullInfo.character_info.level));
			TestPlayer->InvenComp->MenuInven->Wbp_ChaView->ExpCha->SetText
			(FText::AsNumber(UserFullInfo.character_info.current_exp));
			TestPlayer->InvenComp->MenuInven->Wbp_ChaView->MaxExpCha->SetText
			(FText::AsNumber(UserFullInfo.character_info.max_exp));

			auto* MoveComp = TestPlayer->GetCharacterMovement();
			MoveComp->GravityScale = 0.0f;
			TestPlayer->GetCharacterMovement()->GravityScale = 0.0f;
			
			UWorldGi* WorldGi = Cast<UWorldGi>(GetWorld()->GetGameInstance());
			if(WorldGi->bLoginMe == true && TestPlayer && UserFullInfo.character_info.position.x != 0)
			{
				TestPlayer->SetActorLocation(FVector(UserFullInfo.character_info.position.x,
				UserFullInfo.character_info.position.y,UserFullInfo.character_info.position.z + 500));
			}
			FTimerHandle TimerHandle;
			GetWorld()->GetTimerManager().SetTimer(TimerHandle,[this,MoveComp]()
			{
				MoveComp->GravityScale = 1.0f;;
			},4.0f,false);
		}
	});
	httpRequest->ProcessRequest();
}

void ULoginComp::LoadEquipItem()
{
	for (int32 i = 0; i < UserFullInfo.equipment_info.item_list.Num() ; i++)
	{
		for (UWidget* Widget : TestPlayer->InvenComp->MenuInven->WBP_EquipInven->LeftBox->GetAllChildren())
		{
			if (USlotEquip* SlotEquip = Cast<USlotEquip>(Widget)) // 1Î≤àÎ∂ÄÌÑ∞ 5Î≤àÍπåÏßÄ Ïä¨Î°Ø ÎèàÎã§
			{
				TArray<FName>RawNames = SlotEquip->ItemTable->GetRowNames();
			    for (FName RawName : RawNames)
			    {
			    	FItemStructTable* ItemStructTable = SlotEquip->ItemTable->FindRow<FItemStructTable>(RawName,"Î°úÍ∑∏Ïù∏Ïª¥ÌîÑ");
			    	if (UserFullInfo.equipment_info.item_list[i].item_id == RawName &&
			    		static_cast<int32>(SlotEquip->SlotType) == ItemStructTable->ItemIndex)
			    	{
			    		TestPlayer->InvenComp->Server_EquipItem(*ItemStructTable,SlotEquip->SlotType);
			    		SlotEquip->ItemStructTable = *ItemStructTable;
			    		SlotEquip->SlotImageUpdate();
			    		break;
			    	}
			    }
			}
		}
	}
}

void ULoginComp::LoadInvenItem()
{
	if (!TestPlayer -> IsLocallyControlled()){return;}
	
	// TestPlayer->InvenComp->SetGold(UserFullInfo.inventory_info.gold);
	TestPlayer->InvenComp->SetGold(0);
	if (USlot* Slot = Cast<USlot>(TestPlayer->InvenComp->MenuInven->WBP_ItemInven->WrapBox->GetChildAt(0)))
	{
		TArray<FName>RawNames = Slot->ItemTable->GetRowNames();
		for (int32 i = 0; i < UserFullInfo.inventory_info.item_list.Num(); i++)
		{
			for (FName RawName : RawNames)
			{
				FItemStructTable* ItemStructTable = Slot->ItemTable->FindRow<FItemStructTable>(RawName,"LoginComp");
				if (ItemStructTable->Item_Id == UserFullInfo.inventory_info.item_list[i].item_id)
				{
					USlot* SlotInvel = Cast<USlot>(TestPlayer->InvenComp->MenuInven->
						WBP_ItemInven->WrapBox->GetChildAt(i));
					SlotInvel->ItemStructTable = *ItemStructTable;
					SlotInvel->SlotImageUpdate();
				}
			}
		}
	}
}



void ULoginComp::HttpCreatePost(FString CharacterName)
{
	FHttpRequestRef httpRequest = FHttpModule::Get().CreateRequest();
	FNgrok Ngrok;

	FString Endpoint = FString::Printf(TEXT("%s/characters/create"), *Ngrok.Ngrok);
	httpRequest->SetURL(Endpoint);
	
	httpRequest->SetVerb("POST");
	httpRequest->SetHeader(TEXT("Content-Type"), TEXT("application/json"));

	FCreateStruct CreateStruct;
	
	CreateStruct.user_id = UserFullInfo.user_id;
	CreateStruct.character_name = CharacterName;

	FString JsonString;
	FJsonObjectConverter::UStructToJsonObjectString(CreateStruct, JsonString);
	UE_LOG(LogTemp,Display,TEXT("Î°úÍ∑∏Ïù∏Ïª¥ÌîÑ Json String ÏèòÍ∏∞Ï†Ñ : %s"),*JsonString);
	httpRequest->SetContentAsString(JsonString);
	
	httpRequest->OnProcessRequestComplete().BindLambda([this](FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bProcessedSuccessfully)
	{
		if (bProcessedSuccessfully)
		{
			FCreateStructGet CreateStructGet;
			FString JsonString = HttpResponse->GetContentAsString();
			UE_LOG(LogTemp,Warning,TEXT("Î°úÍ∑∏Ïù∏Ïª¥ÌîÑ Ï∫êÎ¶≠ÌÑ∞ ÏÉùÏÑ± ÏÑ±Í≥µ %s"),*JsonString);
			
			FJsonObjectConverter::UStructToJsonObjectString(CreateStructGet,JsonString);
			character_id = CreateStructGet.character_id;
		}
		else
		{
			UE_LOG(LogTemp,Warning,TEXT("Î°úÍ∑∏Ïù∏Ïª¥ÌîÑ Ï∫êÎ¶≠ÌÑ∞ ÏÉùÏÑ± Ïã§Ìå® %d"),HttpResponse->GetResponseCode());
		}
	});
	httpRequest->ProcessRequest();
}

void ULoginComp::ConnectWebSocket()
{
	const FString URL = FString::Printf(TEXT(
		"wss://0b55-221-148-189-129.ngrok-free.app/service1/ws/characters/create/%s"),*UserFullInfo.user_id);
	
	UE_LOG(LogTemp,Warning,TEXT("LoginComp WebSocket Ïó∞Í≤∞Îêú Ï£ºÏÜå[%s]"),*URL)
	const FString Protocol = TEXT("");
	
	WebSocket = FWebSocketsModule::Get().CreateWebSocket(URL, Protocol);
	// Ïó∞Í≤∞ ÏÑ±Í≥µ
	WebSocket->OnConnected().AddUObject(this, &ULoginComp::OnWebSocketConnected);
	// Î©îÏãúÏßÄ ÏàòÏã†
	WebSocket->OnMessage().AddUObject(this, &ULoginComp::OnWebSocketMessage);
	// ÏóêÎü¨ Ï≤òÎ¶¨
	WebSocket->OnConnectionError().AddUObject(this, &ULoginComp::OnWebSocketConnectionError);
	// Ï¢ÖÎ£å Ï≤òÎ¶¨
	WebSocket->OnClosed().AddUObject(this, &ULoginComp::OnWebSocketClosed);
	// Ïã§Ï†ú Ïó∞Í≤∞ ÏãúÎèÑ
	WebSocket->Connect();
}

void ULoginComp::OnWebSocketConnected()
{
	UE_LOG(LogTemp, Log, TEXT("‚úÖ LoginComp WebSocket Connected!"));
}

void ULoginComp::OnWebSocketMessage(const FString& Msg)
{
	UE_LOG(LogTemp, Warning, TEXT("LoginComp ÏõπÏÜåÏºì Î©îÏãúÏßÄ [%s]"), *Msg);
	UiMain->Wbp_UiInitMain->InitResponse->SetText(FText::FromString(Msg));
}

void ULoginComp::OnWebSocketConnectionError(const FString& Error)
{
	UE_LOG(LogTemp, Warning, TEXT("LoginComp ÏõπÏÜåÏºì ÏóêÎü¨ [%s]"), *Error);
}

void ULoginComp::SendInitStringWebSocket(const FString& Message)
{
	if (WebSocket.IsValid() && WebSocket->IsConnected())
	{
		WebSocket->Send(Message);
		UE_LOG(LogTemp, Log, TEXT("‚ñ∂ Sent via WS: %s"), *Message);
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("WebSocket not connected!"));
	}
}

void ULoginComp::OnWebSocketClosed(int32 StatusCode, const FString& Reason, bool bWasClean)
{
	UE_LOG(LogTemp,Warning,TEXT("üîíLoginCOmp ÏõπÏÜåÏºì Closed: Code=%d Reason=%s Clean=%d"), StatusCode, *Reason, bWasClean);
}



// if (APlayerController* PC = Cast<APlayerController>(TestPlayer->GetController()))
// { if (PC->WasInputKeyJustPressed(EKeys::C)) // C Ï∫êÎ¶≠ÌÑ∞ ÏÉùÏÑ± ÏöîÏ≤≠
// 	{   UE_LOG(LogTemp,Display,TEXT("Input C Ï∫êÎ¶≠ÌÑ∞ ÏÉùÏÑ± ÏöîÏ≤≠ Key JustPressed"));
// 	    HttpCreatePost();
// 	}
// }

// DrawDebugString(GetWorld(),TestPlayer->GetActorLocation() + FVector(0, 0, 100),
// FString::Printf(TEXT("LoginComp ÎÇòÏùò UserId [%s] \n "
// 				              "LoginComp ÎÇòÏùò CharacterId [%s]"),*UserFullInfo.user_id, *UserFullInfo.character_info.character_id),
// 				  nullptr,FColor::Red,0.f,false);

// if (APlayerController* PC = Cast<APlayerController>(TestPlayer->GetController()))
// { if (PC->WasInputKeyJustPressed(EKeys::M)) // M Ï∫êÎ¶≠ÌÑ∞ ÏÉùÏÑ± ÎÇ¥ Ï†ïÎ≥¥ ÏöîÏ≤≠
// {   UE_LOG(LogTemp,Display,TEXT("Input M ÎÇ¥ Ï†ïÎ≥¥ Ï£ºÏÖà Key JustPressed"));
// 	HttpMePost();
// }
// }

// if (APlayerController* PC = Cast<APlayerController>(TestPlayer->GetController()))
// { if (PC->WasInputKeyJustPressed(EKeys::N)) // N ÎÇ¥ÏïÑÏù¥ÌÖú Ï£ºÏÖà
// 	{   UE_LOG(LogTemp,Display,TEXT("Input N Ïû•ÎπÑÏïÑÏù¥ÌÖú Î∂ôÏù¥Í∏∞ ÌÖåÏä§Ìä∏"));
// 	if (UWorldGi* WorldGi = Cast<UWorldGi>(GetWorld()->GetGameInstance()))
// 	{
// 		WorldGi->EquipActor(TestPlayer);
// 	}
// 	}
// }

// if (APlayerController* PC = Cast<APlayerController>(TestPlayer->GetController()))
// { if (PC->WasInputKeyJustPressed(EKeys::B)) // B ÏõπÏÜåÏºìÏó∞Í±∏
// {
// 	ConnectWebSocket();
// 	UE_LOG(LogTemp,Display,TEXT("Input B ÏõπÏÜåÏºì Ïó∞Í≤∞ Key JustPressed"));
// }
// }


// if (bQuest == true)
// {
// 	if (AQuestOrderActor* QuestOrderActor = Cast<AQuestOrderActor>(NpcNet->QuestActorComponent->GetChildActor()))
// 	{
// 		if (QuestOrderActor->QuestType == EQuestType::B_NetNpcHearty)
// 		{
// 			TestPlayer->InvenComp->MenuInven->Wbp_UiWorldMap->NextQuestType(EQuestType::C_NetNpcScared);
// 		}
// 		else if (QuestOrderActor->QuestType == EQuestType::C_NetNpcScared)
// 		{
// 			TestPlayer->InvenComp->MenuInven->Wbp_UiWorldMap->NextQuestType(EQuestType::D_Store);
// 		}
// 	}
// 	NpcNet->OpenQuest();
// 	bQuest = false;
// }
// else
// {
// 	if (!NpcNet || !NpcNet->UIPost) return;
// 	NpcNet->UIPost->RemoveFromParent();
// 	bQuest = true;
// }